#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: LemonBench

on:
#  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
#  schedule:
#    - cron: 0 5 * * 2,5


jobs:
  build:
    runs-on: ubuntu-18.04
      run:curl -fsSL https://ilemonrain.com/download/shell/LemonBench.sh | bash -s fast
